TalkingData AdTracking Fraud Detection Challenge Submission
================================

 A TalkingData, a maior plataforma de big data independente da China, cobre mais de 70% dos dispositivos móveis ativos em todo o país. Eles lidam com 3 bilhões de cliques por dia, dos quais 90% são potencialmente fraudulentos. Sua abordagem atual para impedir fraudes de cliques para desenvolvedores de aplicativos é medir a jornada do clique de um usuário em todo o portfólio e sinalizar endereços IP que produzem muitos cliques, mas nunca acabam instalando aplicativos. Com essas informações, eles criaram uma lista negra de IP e uma lista negra de dispositivos.

  Embora bem-sucedidos, eles querem estar sempre um passo à frente dos fraudadores e pediram ajuda à comunidade de Kaggle para desenvolver ainda mais a solução. Em sua segunda competição com a Kaggle, você é desafiado a criar um algoritmo que prevê se um usuário fará o download de um aplicativo depois de clicar em um anúncio de aplicativo para dispositivos móveis. Para dar suporte à sua modelagem, eles forneceram um conjunto de dados generoso cobrindo aproximadamente 200 milhões de cliques em 4 dias!

Bibliotecas
-----------

In [1]:
import sklearn
import numpy as np 
import pandas as pd

In [2]:
%matplotlib inline

Leitura dos dados
-------------------

In [74]:
data = pd.read_csv('train.csv')
#print data
y = data['is_attributed']
X = data.drop(['is_attributed', 'click_time', 'attributed_time'], axis=1)

In [16]:
print data

               ip  app  device  os  channel           click_time  \
0           83230    3       1  13      379  2017-11-06 14:32:21   
1           17357    3       1  19      379  2017-11-06 14:33:34   
2           35810    3       1  13      379  2017-11-06 14:34:12   
3           45745   14       1  13      478  2017-11-06 14:34:52   
4          161007    3       1  13      379  2017-11-06 14:35:08   
5           18787    3       1  16      379  2017-11-06 14:36:26   
6          103022    3       1  23      379  2017-11-06 14:37:44   
7          114221    3       1  19      379  2017-11-06 14:37:59   
8          165970    3       1  13      379  2017-11-06 14:38:10   
9           74544   64       1  22      459  2017-11-06 14:38:23   
10         172522    3       1  25      379  2017-11-06 14:38:27   
11         105861    3       1  13      379  2017-11-06 14:38:51   
12         210962    3       1  19      379  2017-11-06 14:39:29   
13         124979    3       1  18      379  201

Resumo estatítico
--------------------

In [17]:

print data.describe()

                 ip           app        device            os       channel  \
count  1.849039e+08  1.849039e+08  1.849039e+08  1.849039e+08  1.849039e+08   
mean   9.087604e+04  1.201131e+01  2.172325e+01  2.267702e+01  2.685789e+02   
std    6.952789e+04  1.480521e+01  2.593326e+02  5.525282e+01  1.295882e+02   
min    1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    4.024500e+04  3.000000e+00  1.000000e+00  1.300000e+01  1.400000e+02   
50%    7.962200e+04  1.200000e+01  1.000000e+00  1.800000e+01  2.580000e+02   
75%    1.182470e+05  1.500000e+01  1.000000e+00  1.900000e+01  3.790000e+02   
max    3.647780e+05  7.680000e+02  4.227000e+03  9.560000e+02  5.000000e+02   

       is_attributed  
count   1.849039e+08  
mean    2.470721e-03  
std     4.964491e-02  
min     0.000000e+00  
25%     0.000000e+00  
50%     0.000000e+00  
75%     0.000000e+00  
max     1.000000e+00  


Validação Cruzada
------------------

In [69]:
#from sklearn.cross_validation import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


Criação e treinamento do modelo
-----------------------------------

In [19]:
print np.unique(y, return_counts=True)

(array([0, 1]), array([184447044,    456846]))


In [75]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X, y) 


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

(array([0, 1]), array([74839,   161]))


Prevendo classificação dos dados
-------------------------------------

In [76]:
X_test = pd.read_csv('test.csv')

In [22]:
#print X_test.shape

(18790469, 7)


In [77]:
X_test.drop(['click_id', 'click_time'], axis=1, inplace=True)
pred = clf.predict(X_test)
print pred

[0 0 0 ... 0 0 0]


Acurácia das classificações feitas
---------------------------------------

In [78]:
print np.unique(pred, return_counts=True)

(array([0, 1]), array([18759990,    30479]))


Guardando resultados
------------------------

In [79]:

df = pd.DataFrame(data=pred, columns=[ 'is_attributed'])
df.index.name = "click_id"
df.is_attributed = df.is_attributed.astype(int)


In [80]:

# print(df.is_attributed.unique())
df.to_csv("saida.csv")


In [82]:
print df.head()

          is_attributed
click_id               
0                     0
1                     0
2                     0
3                     0
4                     0


In [51]:
oi = pd.read_csv('saida.csv')

In [52]:
print oi.shape

(18790469, 2)


In [53]:
print oi.head()

   click_id  is_attributed
0         0              0
1         1              0
2         2              0
3         3              0
4         4              0
